# Configuração dos servidores MCP
servers:
  - name: dummy
    url: http://localhost:7000
    enabled: true
    timeout: 30
    retry_attempts: 3

    # 🔥 Novos campos:
    endpoints:
      health: /health
      tools: /tools
      call: /call

    response_map:
      tools_key: ""             # se a resposta já for lista, deixa vazio
      tool_name_field: name
      tool_desc_field: description

    payload_map:
      tool_field: tool
      args_field: arguments

# Configurações do Hub
hub:
  host: "0.0.0.0"
  port: 8000
  debug: true
  log_level: "INFO"
  cors_enabled: true
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"

# Cache settings
cache:
  enabled: true
  ttl: 300  # 5 minutos
  max_size: 1000

# Rate limiting
rate_limit:
  enabled: true
  requests_per_minute: 100
  burst_size: 10
